QLK.Website/Controllers/ExInputController.cs
using ClosedXML.Excel;
using PagedList;
using QLK.Website.Model;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLK.Website.Controllers
{
    public class ExInputController : Controller
    {
        ListExInput Ex = new ListExInput();
        QLKEntities db = new QLKEntities();
        public ActionResult Index(string SearchString, string currentFilter, int? page, DateTime ? datein, DateTime ? dateout )
        {

            if (Request.Cookies["Username"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            
            var dtin = DateTime.Parse("1/1/2020");
            var datei = datein ?? dtin;
            var dateo = dateout?? DateTime.Now;
            ViewBag.datein = datei;
            ViewBag.dateout = dateo;
            ViewBag.datenow = DateTime.Now;
            Session["search"] = SearchString;
            Session["dtin"] = datei;
            Session["dtout"] = dateo;

            if (db.Detailimportcoupons != null)
            {
                var sl = db.Detailimportcoupons.Sum(o => o.Quantity);
                var dem = db.Detailimportcoupons.Count();
                ViewBag.sl = sl;
                ViewBag.dem = dem;
            }
            else
            {
                ViewBag.sl = 0;
                ViewBag.dem = 0;
            }    
            var listrExInput = new List<ExInput>();

            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = currentFilter;
               
            }
            if (!string.IsNullOrEmpty(SearchString))
            {

                listrExInput = Ex.ListExinput(SearchString, datei, dateo);
            }
            else
            {
                listrExInput = Ex.ListExinput(datei, dateo);
            }
            ViewBag.currentFilter = SearchString;
            ViewBag.UploadPhotoProcut = db.UploadPhotoProducts.ToList();
            int pageSize = 8;
            int pageNumber = (page ?? 1);

            listrExInput = listrExInput.OrderByDescending(n => n.DetailsImport).ToList();

            return View(listrExInput.ToPagedList(pageNumber, pageSize));
        }

        public FileResult Export()
        {

            var str = Session["search"];
            var datein = Session["dtin"];
            var dateout = Session["dtout"];
                QLKEntities db = new QLKEntities();
                System.Data.DataTable dt = new System.Data.DataTable("Grid");
                dt.Columns.AddRange(new DataColumn[9] {
                                            new DataColumn("Mã chi tiết phiếu nhập"),
                                               new DataColumn("Ngày nhập"),
                                             new DataColumn("Tên mặt hàng"),
                                               new DataColumn("Tên loại hàng"),
                                            new DataColumn("Tên nhà cung cấp"),
                                            new DataColumn("Đơn vị tính"),
                                             new DataColumn("Đơn giá"),
                                             new DataColumn("Số lượng"),
                                              new DataColumn("Thành tiền")
                });

            var kt = db.DetailBills.FirstOrDefault(o => o.Quantity == null);
            if (kt != null)
            {
                var kt1 = db.Detailimportcoupons.FirstOrDefault(o => o.Quantity == null);
                if (kt1 != null)
                {
                    int detailquantity = (int)db.DetailBills.Sum(o => o.Quantity);
                    int importquantity = (int)db.Detailimportcoupons.Sum(p => p.Quantity);
                    int tong = importquantity - detailquantity;

                }
                else
                {
                    int detailquantity = 0;
                    int importquantity = (int)db.Detailimportcoupons.Sum(p => p.Quantity);
                    int tong = importquantity - detailquantity;
                }
            }

            else
            {
                int detailquantity = 0;
                int importquantity = 0;
                int tong = detailquantity - importquantity;
            }
            List<ExInput> exInputs = new List<ExInput>();
                
            if (str != null)
            {
                var temp = db.Detailimportcoupons.Where(o => (o.Unit.Contains((string)str) || o.Product.ProductName.Contains((string)str) || o.ProductID.Contains((string)str) ||
               o.Product.Category.CategoryName.Contains((string)str) || o.Product.Supplier.SupplierName.Contains((string)str)) && (o.Importcoupon.Date >= (DateTime)datein && o.Importcoupon.Date <= (DateTime)dateout));

                foreach (var ovbj in temp)
                {

                    var Pr = db.Products.FirstOrDefault(o => o.ProductID == ovbj.ProductID);
                    var sup = db.Suppliers.FirstOrDefault(o => o.SupplierID == Pr.SupplierID);
                    var im = db.Importcoupons.FirstOrDefault(o => o.ImportID == ovbj.ImportID);
                    var cate = db.Categories.FirstOrDefault(o => o.CategoryID == Pr.CategoryID);
                    exInputs.Add(new ExInput
                    {

                        Photo = Pr.Photo,
                        DetailsImport = ovbj.DetailimportID,
                        ProductID = Pr.ProductID,
                        CategoryID = cate.CategoryID,
                        ImportID = (int)ovbj.ImportID,
                        ProductName = Pr.ProductName,
                        SupplierName = sup.SupplierName,
                        CategoryName = cate.CategoryName,
                        Date = (DateTime)im.Date,
                        Unit = ovbj.Unit,
                        Price = ovbj.Price,
                        QuantityIm = (int)ovbj.Quantity,
                        Tolalpricein = ovbj.Price * (int)ovbj.Quantity
                    });
                }

                foreach (var ovjb in exInputs)
                {
                    dt.Rows.Add(ovjb.DetailsImport, ovjb.Date, ovjb.ProductName, ovjb.CategoryName, ovjb.SupplierName, ovjb.Unit, ovjb.Price, ovjb.QuantityIm, ovjb.Tolalpricein);
                }
            }
            else
            {
                var temp = db.Detailimportcoupons.Where(o=> o.Importcoupon.Date >= (DateTime)datein && o.Importcoupon.Date <= (DateTime)dateout);
                foreach (var ovbj in temp)
                {

                    var Pr = db.Products.FirstOrDefault(o => o.ProductID == ovbj.ProductID);
                    var sup = db.Suppliers.FirstOrDefault(o => o.SupplierID == Pr.SupplierID);
                    var im = db.Importcoupons.FirstOrDefault(o => o.ImportID == ovbj.ImportID);
                    var cate = db.Categories.FirstOrDefault(o => o.CategoryID == Pr.CategoryID);
                    exInputs.Add(new ExInput
                    {

                        Photo = Pr.Photo,
                        DetailsImport = ovbj.DetailimportID,
                        ProductID = Pr.ProductID,
                        CategoryID = cate.CategoryID,
                        ImportID = (int)ovbj.ImportID,
                        ProductName = Pr.ProductName,
                        SupplierName = sup.SupplierName,
                        CategoryName = cate.CategoryName,
                        Date = (DateTime)im.Date,
                        Unit = ovbj.Unit,
                        Price = ovbj.Price,
                        QuantityIm = (int)ovbj.Quantity,
                        Tolalpricein = ovbj.Price * (int)ovbj.Quantity
                    });
                }

                foreach (var ovjb in exInputs)
                {
                    dt.Rows.Add( ovjb.DetailsImport, ovjb.Date, ovjb.ProductName, ovjb.CategoryName, ovjb.SupplierName,ovjb.Unit,ovjb.Price, ovjb.QuantityIm,ovjb.Tolalpricein);
                }
            }    
  
                using (XLWorkbook wb = new XLWorkbook())
                {
                    wb.Worksheets.Add(dt);
                    using (MemoryStream stream = new MemoryStream())
                    {
                        wb.SaveAs(stream);
                        return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "BaoCaoNhapKho.xlsx");
                    }
                }

            
        }
    }    
            
}

QLK.Website/Views/ExInput/Index.cshtml
@*@model IEnumerable<QLK.Website.Model.ExInput>*@
@using PagedList.Mvc;
@model PagedList.IPagedList<QLK.Website.Model.ExInput>

@{
    ViewBag.Title = "Báo cáo nhập hàng";
}
<div class="row">
    <div class="col-md-12">
        <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title">@ViewBag.Title</h3>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            @using (Html.BeginForm("Export", "ExInput", FormMethod.Post))
                            {
                                <div>
                                    <button class="btn btn-success">Xuất Excel</button>
                                </div>
                            }
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="text-right">
                            @using (Html.BeginForm("Index", "ExInput", FormMethod.Get))
                            {<div class="row">
                                    @*<div class="col-lg-4">

                                        <div class='input-group date' id='datetimepicker6'>
                                            <input type='text' name="datein" class="form-control" />
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="col-lg-4">
                                        <div class='input-group date' id='datetimepicker7'>
                                            <input type='text' name="dateout" class="form-control" />
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                        </div>

                                    </div>*@
                                 <div class="col-lg-4">
                                     <input type="hidden" id="datein" name="datein" />
                                     <input type="hidden" id="dateout" name="dateout" />
                                     <input type="text" name="datefilter" value="@ViewBag.datenow - @ViewBag.datenow" class="form-control text-center" />
                                 </div>
                                    <div class="col-lg-6">
                                       
                                            <div class="col-lg-9 ">
                                                <input type="text" class="form-control" name="SearchString" />
                                            </div>
                                            <div class="col-lg-2">
                                                <input type="submit" value="Tìm kiếm" class="btn btn-warning" />
                                            </div>

                                    </div>
                                </div>



                            }
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th style="text-align: center">
                                            Ảnh
                                        </th>
                                        <th style="text-align: center">
                                            Mã chi tiết phiếu nhập
                                        </th>
                                     
                                        <th style="text-align: center">
                                            Ngày nhập
                                        </th>
                                        <th style="text-align: center">
                                            Tên mặt hàng
                                        </th>
                                        <th style="text-align: center">
                                            Tên loại mặt hàng
                                        </th>
                                        <th style="text-align: center">
                                            Tên nhà cung cấp
                                        </th>
                                        <th style="text-align: center">
                                            Đơn vị tính
                                        </th>
                                        <th style="text-align: center">
                                            Đơn giá
                                        </th>
                                        <th style="text-align: center">
                                            Số lượng
                                        </th>
                                        <th style="text-align: center">
                                            Thành tiền
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td>
                                            @foreach (var ite in ViewBag.UploadPhotoProcut)
                                            {
                                                if (ite.IDProduct == item.ProductID)
                                                {
                                                    <img src="@Url.Content(ite.Path)" style="height:50px;width:50px">
                                                }


                                            }
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.DetailsImport)
                                        </td>
                                        
        
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Date)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ProductName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CategoryName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.SupplierName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Unit)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Price) đ
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.QuantityIm)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Tolalpricein) đ
                                        </td>
                                    </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div style="color:red;">
    <p>
        Tổng có @ViewBag.dem phiếu nhập
    </p>
    <p>
        Tổng số lượng nhập: @ViewBag.sl
    </p>
</div>

<div class="text-center">
    Trang @(Model.PageCount < Model.PageNumber ? 0: Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter, datein = ViewBag.datein, dateout = ViewBag.dateout }))
</div>

<script>
    $(function () {

        var date = '1-30-2021';
        var dateNow = new Date();
        $('#datetimepicker6').datetimepicker({
            defaultDate: date,
           /*format: 'DD/MM/YYYY',*/
        });


        $('#datetimepicker7').datetimepicker({
            defaultDate: dateNow,
         /*  format: 'DD/MM/YYYY',*/
            useCurrent: false
        });
        $("#datetimepicker6").on("dp.change", function (e) {
            $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
        });
        $("#datetimepicker7").on("dp.change", function (e) {
            $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
        });
    });
    $(function () {

        $('input[name="datefilter"]').daterangepicker({
            autoUpdateInput: false,
            locale: {
                cancelLabel: 'Clear'
            }
        });

        $('input[name="datefilter"]').on('apply.daterangepicker', function (ev, picker) {
            //alert('â');
            $(this).val(picker.startDate.format('MM/DD/YYYY') + '-' + picker.endDate.format('MM/DD/YYYY'));
            $("#datein").val(picker.startDate.format('MM/DD/YYYY'));
            $("#dateout").val(picker.endDate.format('MM/DD/YYYY'));
        });

        $('input[name="datefilter"]').on('cancel.daterangepicker', function (ev, picker) {
            $(this).val('');
        });

    });
</script>