QLK.Website/Controllers/WarehouseController.cs
using PagedList;
using QLK.Website.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLK.Website.Controllers
{
    public class WarehouseController : Controller
    {
        QLKEntities db = new QLKEntities();
        ListWarehouse p = new ListWarehouse();
        Bill b = new Bill();
        Importcoupon i = new Importcoupon();
        // GET: Product
        public ActionResult Index(string SearchString, string currentFilter, int ? page)
        {
            //if (Session["Username"] == null)
            //{
            //    return RedirectToAction("Login", "Account");
            //}
            if (Request.Cookies["Username"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var ware = db.Warehouses;
            ViewBag.Ware = ware;
            var ListWare = new List<Warehouse>();
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = currentFilter;
            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                ListWare = db.Warehouses.Where(o => o.WarehouseName.Contains(SearchString)).ToList();
            }
            else
            {
                ListWare = db.Warehouses.ToList();
            }
            ViewBag.currentFilter = SearchString;
            int pageSize = 8;
            int pageNumber = (page ?? 1);

            ListWare = ListWare.OrderByDescending(n => n.WarehouseID).ToList();

            return View(ListWare.ToPagedList(pageNumber, pageSize));



        }
        //tao 1 product
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public JsonResult Create(Warehouse warehouse)
        {
            bool result = false;
            if (warehouse.WarehouseName != null && warehouse.Soluong != null)
            {
                p.Add(warehouse);
                result = true;
            }
            return Json(result,JsonRequestBehavior.AllowGet);
            
        }
        //sua product theo id
        //public ActionResult Edit(int id)
        //{

        //    return View(p.listWareID(id));

        //}

        //[HttpPost]
        //public ActionResult Edit(Warehouse warehouse)
        //{

        //    if (warehouse.WarehouseName != null && warehouse.Soluong != null)
        //        {
        //            p.Edit(warehouse);
        //            return RedirectToAction("index");
        //        }

        //    return View();
        //}
        public ActionResult Edit(int id)
        {
          
            var model = db.Warehouses.Where(o => o.WarehouseID == id).FirstOrDefault();
            return PartialView("EditPartial", model);
        }

        [HttpPost]
        public JsonResult Edit(Warehouse warehouse)
        {
          
            bool result = false;
            if (warehouse.WarehouseName != null && warehouse.Soluong != null)
            {
                p.Edit(warehouse);
                result = true;
            }
            return Json(result, JsonRequestBehavior.AllowGet);

        }
        public JsonResult Delete(int id)
        {
            bool result = false;
            var input = db.Warehouses.Where(o => o.WarehouseID == id);
            if (input != null)
            {
                var bill = db.Bills.FirstOrDefault(o => o.WarehouseID == id);
                var imp = db.Importcoupons.FirstOrDefault(o => o.WarehouseID == id);
                if (bill == null && imp == null)
                {
                    p.Delete(id);
                    result = true;
                }

            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

QLK.Website/Views/Warehouse/Create.cshtml
@model QLK.Website.Model.Warehouse

@{
    ViewBag.Title = "Create";
}
<h2 class="text-center">Tạo mới kho</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.WarehouseName, "Tên kho",htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.WarehouseName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.WarehouseName, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.WarehouseName)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Soluong,"Max", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Soluong, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Soluong, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row">
        <div class=" text-center col-md-6">
            <input type="submit" value="Create" class="btn btn-primary " />
        </div>
        <div class="btn btn-danger">
            @Html.ActionLink("Trở về", "Index")

        </div>
    </div>
</div>
}

QLK.Website/Views/Warehouse/Delete.cshtml
@model QLK.Website.Model.Warehouse

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Warehouse</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WarehouseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WarehouseName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Soluong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soluong)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete"  onclick="return confirm('Bạn muôn xóa không??')"  class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QLK.Website/Views/Warehouse/Edit.cshtml
@model QLK.Website.Model.Warehouse
@{
    ViewBag.Title = "Chỉnh sửa kho";
}
<div class="row">
    <!-- left column -->
    <div class="col-md-12">
        <!-- general form elements -->
        <!-- Form Element sizes -->
        <div class="box box-success">
            <div class=" with-border">
                <h3 class="box-title">@ViewBag.Title</h3>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.WarehouseID)

                    <div class="form-group">

                        @Html.LabelFor(model => model.WarehouseName, "Tên kho", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.WarehouseName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.WarehouseName, "", new { @class = "text-danger" })

                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Soluong, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Soluong, new { htmlAttributes = new { @class = "form-control", t} })
                            @Html.ValidationMessageFor(model => model.Soluong, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row">
                        <div class=" text-center col-md-6">
                            <input type="submit" value="Save" class="btn btn-success" />
                        </div>
                        <div class="btn btn-danger">
                            @Html.ActionLink("Trở về", "Index")

                        </div>
                    </div>
                </div>
            }
            <br />
        </div>
     </div>
 </div>





               

QLK.Website/Views/Warehouse/EditPartial.cshtml
@model QLK.Website.Model.Warehouse

@{
    Layout = null;
}
<div>
    <form id="myForm">
        @Html.HiddenFor(model=> model.WarehouseID)
        <div class=" form-group">
            <label>Tên kho</label>
            @Html.TextBoxFor(model => model.WarehouseName, new { @class = "form-control", @placeholder = "" })
        </div>
    <div class="form-group">
        <label>Số lượng</label>
        @Html.TextBoxFor(model => model.Soluong, new { @class = "form-control", @placeholder = "" , Type="number"})
    </div>
        <div class="text-right">
            <a href="#" id="btnSubmit" class="btn btn-primary">Lưu</a>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Trở lại</button>
        </div>
    </form>
</div>
<script>
    $(document).ready(function () {
        $("#btnSubmit").click(function () {

            var myformdata = $("#myForm").serialize();
            $.ajax({

                type: "POST",
                url: "/Warehouse/Edit",
                data: myformdata,
                success: function (data) {
                    if (data == true) {

                        window.location.href = "/Danh-sach-kho";
                    }
                    else {
                        alert("Lỗi! không thể chỉnh sửa mặt hàng này!");
                    }

                }

            })
        })
    })
</script>

QLK.Website/Views/Warehouse/Index.cshtml
@*@model QLK.Website.Model.Warehouse*@
@using PagedList.Mvc;
@model PagedList.IPagedList<QLK.Website.Model.Warehouse>

@{
    ViewBag.Title = "Danh sách kho";
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title">@ViewBag.Title</h3>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-lg-8">
                        <p>
                            @*<a href="@Url.Action("Create")" class="btn btn-success">*@
                            <a href="#" class="btn btn-success" data-toggle="modal" data-target="#wareModal"> <i class="fa fa-plus"></i>Thêm mới</a>
                        </p>
                    </div>
                    <div class="col-lg-4">

                    @using (Html.BeginForm("Index", "Warehouse", FormMethod.Get))
                    {

                        <div class="col-lg-6">
                            <input type="text" class="form-control" name="SearchString" id="SearchString" />
                        </div>
                        <div class="col-lg-3">
                            <input type="submit" value="Tìm kiếm" class="btn btn-warning" />
                        </div>
                    }
                </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>

                                        <th style="text-align: center">
                                            Tên kho
                                        </th>
                                        <th style="text-align: center">
                                            Số lượng
                                        </th>
                                        <th style="text-align: center">
                                            Tác vụ
                                        </th>
                                    </tr>
                                </thead>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @item.WarehouseName
                                        </td>
                                        <td>
                                            @item.Soluong
                                        </td>
                                        <td align="center">
                                            @*<a href="@Url.Action("Edit", new { id = item.WarehouseID })" class="btn btn-success"><i class="fa fa-pencil"></i></a>*@
                                            <a href="#" class="btn btn-success" onclick="EditWare(@item.WarehouseID)"><i class="fa fa-pencil"></i> </a>
                                            <a href="#" class="btn btn-danger" id="showModal" onclick="confirm(@item.WarehouseID)"><i class="fa fa-trash"></i></a>
                                            @*<a onclick="return confirm('Bạn muôn xóa không??')" class="btn btn-danger" href="@Url.Action("Delete", new { id = item.WarehouseID })"><i class="fa fa-trash"></i></a>*@
                                        </td>
                                    </tr>
                                }

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="container">
    <!-- Modal -->
    <div class="modal fade" id="wareModal" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content ">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h1 class="modal-title text-center">Thêm nhà cung cấp</h1>
                </div>
                <div class="modal-body">
                    <!-- source code-->
                    <form id="wareform">
                        <div class="form-group">
                            <label>Tên Kho</label>
                            @*@Html.TextBoxFor(model => model.FirstOrDefault().WarehouseName, new { @class = "form-control", required = "required" })*@
                            <input type="text" name="WarehouseName" class="form-control" required />
                            @Html.ValidationMessageFor(model => model.FirstOrDefault().WarehouseName, "", new { @class = "text-danger" })
                        </div>
                        <div class=" form-group">
                            <label>Số lượng</label>
                            @*@Html.TextBoxFor(model => model.FirstOrDefault().Soluong, new { @class = "form-control", required = "required" })*@
                            <input type="number" name="Soluong" class="form-control" required />
                            @Html.ValidationMessageFor(model => model.FirstOrDefault().Soluong, "", new { @class = "text-danger" })
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <a href="#" id="btnSave" class="btn btn-primary">Lưu</a>
                    @*<a href="#" id="btnCancel" class="btn btn-danger">Canncel</a>*@
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Trở lại</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="editWarehouse">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
                <h3 class="modal-title text-center">Chỉnh sửa kho</h3>
            </div>
            <div class="modal-body" id="myModalBodyDiv3">
            </div>

        </div>
    </div>
</div>


<div class="modal fade " id="deleteware">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title text-center">Thông báo</h3>
            </div>
            <div class="modal-body">
                Bạn có thật sự muốn xóa nó không ??
            </div>
            <div class="modal-footer">
                <a href="#" id="btndeleteconfirm" class="btn btn-primary">Xóa</a>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Trở lại</button>
            </div>
        </div>
    </div>
</div>
<input type="hidden" id="Warehouseid" />


<div class="text-center">
    Trang @(Model.PageCount < Model.PageNumber ? 0: Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))
</div>


<script>
    $(document).ready(function () {
        var error = "lỗi";
        $("#btnSave").click(function () {
            var supplierFormData = $("#wareform").serialize();
            $.ajax({
                type: "POST",
                url: "/Warehouse/Create",
                data: supplierFormData,
                success: function (data) {
                    if (data == true) {
                        alert("Thêm thành công!");
                        window.location.href = "/Danh-sach-kho";
                    }
                    else {
                        alert("Lỗi!! Không thể kho này!");
                    }
                },
            })
        })

        $("#btndeleteconfirm").click(function () {
            var _id = $("#Warehouseid").val();
            $.ajax({
                type: "POST",
                url: "/Warehouse/Delete",
                data: { id: _id },
                success: function (data) {
                    if (data == true) {
                        $("#deleteware").modal('hide');
                        $("#Warehouseid").val(null);

                        window.location.href = "/Danh-sach-kho";
                    }
                    else {
                        alert("Error!! kho này không được xóa!");
                    }
                }

            })
        })
    })
    var confirm = function (id) {
        $("#Warehouseid").val(id);
        $("#deleteware").modal('show');

    }

    var EditWare = function (id) {
        var url = "/Warehouse/Edit/" + id;
        $("#myModalBodyDiv3").load(url, function () {
            $("#editWarehouse").modal("show");

        })

    }
</script>