QLK.Website/Controllers/OutputController.cs
using PagedList;
using QLK.Website.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLK.Website.Controllers
{
    public class OutputController : Controller
    {

        DetailOutput deta = new DetailOutput();
        Output p = new Output();
        QLKEntities db = new QLKEntities();
      
        // GET: Input
        public ActionResult Index(string SearchString, string currentFilter, int ? page, DateTime ? datein, DateTime ? dateout)
        {
      
            if (Request.Cookies["Username"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var k = Session["idoutput"];
            ViewBag._id = k;
            var h = Session["Searchoutput"];
            ViewBag.searchform = h;
            ViewBag.UploadphotoBill = db.UploadPhotoBills.ToList();
            var dtin = DateTime.Parse("1/1/2020");
            var datei = datein ?? dtin;
            var dateo = dateout ?? DateTime.Now;
            ViewBag.datein = datei;
            ViewBag.dateout = dateo;
            ViewBag.datenow = DateTime.Now;
            if (k != null)
            {
                var detailbill = db.DetailBills.Where(o => o.BillID == (int)k).ToList();
                ViewBag.detailbill = detailbill;
            }
            else
            {
                var detailbill = db.DetailBills.ToList();
                ViewBag.detailbill = detailbill;
            }

            ViewBag.pg = Session["page"];

            List<UnitSelectlist> unitSelectlists = new List<UnitSelectlist>();
            var pro = db.Products.ToList();
            foreach (var item in pro)
            {
                if (unitSelectlists.Count() < 1)
                {
                    unitSelectlists.Add(new UnitSelectlist
                    {
                        unit = item.Unit
                    });
                }
                else
                {
                    var kt = unitSelectlists.Where(o => o.unit == item.Unit).ToList();
                    if (kt.Count() < 1)
                    {
                        unitSelectlists.Add(new UnitSelectlist
                        {
                            unit = item.Unit
                        });
                    }

                }

            }
            ViewBag.unit = unitSelectlists.ToList();
            ViewBag.pro = pro;
            var warehouses = db.Warehouses;
            ViewBag.Warehouses = warehouses;
            var bill = db.Bills.ToList();
            ViewBag.bill = bill;
            var ListOutput = new List<Bill>();
            if (SearchString != null)
              {
                page = 1;
               }
                else
                  {
                
                SearchString = currentFilter;
                  }
                 if (!string.IsNullOrEmpty(SearchString))
                {
                    if(datei != null && dateo != null)
                    {
                    ListOutput = db.Bills.Where(o => (o.Warehouse.WarehouseName.Contains(SearchString) || o.BillName.Contains(SearchString)) && (o.Date >= datei && o.Date <= dateo)).ToList();
                    }
                    else
                    {
                    ListOutput = db.Bills.Where(o => o.Warehouse.WarehouseName.Contains(SearchString) || o.BillName.Contains(SearchString)).ToList();
                     }    
                 
                }
                else
                 {
                    if (datei != null && dateo != null)
                    {
                    ListOutput = db.Bills.Where(o=> o.Date >= datei && o.Date <= dateo).ToList();
                    }
                    else
                    {
                    ListOutput = db.Bills.ToList();
                    }    
                 }
            ViewBag.currentFilter = SearchString;
            int pageSize = 4;
            int pageNumber = (page ?? 1);

            ListOutput = ListOutput.OrderByDescending(n => n.BillID).ToList();

            return View(ListOutput.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Create()
        {
            var warehouses = db.Warehouses;
            ViewBag.Warehouses = warehouses;
            return View();
        }
        [HttpPost]
        public JsonResult Create(Bill output, HttpPostedFileBase[] file)
        {
            
            bool result = false;
           
            if (file != null)
            {
                if (output.WarehouseID != null && output.BillName != null)
                {
                    var date = DateTime.Now;
                    output.Date = date;
                    //output.Photo = "~/Image/Img/" + fileName;
                    p.Add(output);
                    result = true;
                }
                foreach (HttpPostedFileBase fl in file)
                {
                    var InputFileName = System.IO.Path.GetFileName(fl.FileName);
                    var ServerSavePath = System.IO.Path.Combine(Server.MapPath("~/Image/Img/") + InputFileName);
                    fl.SaveAs(ServerSavePath);
                    UploadPhotoBill upfl = new UploadPhotoBill();
                    upfl.IdBill = output.BillID;
                    upfl.Path = "~/Image/Img/" + InputFileName;
                    db.UploadPhotoBills.Add(upfl);                 

                }
            }
            db.SaveChanges();

            return Json(new { status = result }, JsonRequestBehavior.AllowGet);
        }
        //sua product theo id
        //public ActionResult Edit(int id)
        //{
        //    return View(p.listBillID(id));
        //}

        //[HttpPost]
        //public ActionResult Edit(Bill output)
        //{
        //    if (output.Date != null && output.WarehouseID != null)
        //    {
        //        p.Edit(output);
        //        return RedirectToAction("Index");
        //    }
        //    else
        //        return View();

        //}
        public ActionResult Edit(int id)
        {
            ViewBag.UploadphotoBill = db.UploadPhotoBills.ToList();
            var inpu = db.Warehouses.ToList();
            ViewBag.ware = inpu;
            var model = db.Bills.Where(o => o.BillID == id).FirstOrDefault();
            return PartialView("EditOpPartial", model);
        }

        [HttpPost]
        public JsonResult Edit(Bill Ipc , HttpPostedFileBase[] file)
        {
            var inpu = db.Warehouses.ToList();
            ViewBag.ware = inpu;
            bool result = false;

            if (Ipc.WarehouseID != null && Ipc.BillName != null)
            {
                p.Edit(Ipc);
                result = true;
            }
            if(file!=null)
            {
                foreach (HttpPostedFileBase fl in file)
                {
                    var InputFileName = System.IO.Path.GetFileName(fl.FileName);
                    var ServerSavePath = System.IO.Path.Combine(Server.MapPath("~/Image/Img/") + InputFileName);
                    fl.SaveAs(ServerSavePath);
                    UploadPhotoBill upfl = new UploadPhotoBill();
                    upfl.IdBill = Ipc.BillID;
                    upfl.Path = "~/Image/Img/" + InputFileName;
                    db.UploadPhotoBills.Add(upfl);

                }
            }
            db.SaveChanges();
            return Json(result, JsonRequestBehavior.AllowGet);

        }

        //Xoa 1 product
        //public ActionResult Delete(int id)
        //{
        //    var im = db.DetailBills.FirstOrDefault(o => o.BillID == id);
        //    if (im == null)
        //    {
        //        p.Delete(id);
        //        return RedirectToAction("index");
        //    }

        //    return RedirectToAction("index");
        //}

        public JsonResult Delete(int id)
        {
            bool result = false;
            var input = db.Bills.Where(o => o.BillID == id);
            if (input != null)
            {
                var deletephoto = db.UploadPhotoBills.Where(o => o.IdBill == id).ToList();
                if (deletephoto != null)
                {
                    foreach(var item in deletephoto)
                    {
                        db.UploadPhotoBills.Remove(item);
                    }    
                }    
                var kt = db.DetailBills.FirstOrDefault(o => o.BillID == id);
                if (kt == null)
                {
                    p.Delete(id);
                    result = true;
                }

            }
            db.SaveChanges();
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        public PartialViewResult getpaging(int? page)
        {
            var searchfrom = Session["Searchoutput"];
            var kt = Session["idoutput"];
            ViewBag._id = kt;
            var pro = db.Products.ToList();
            List<UnitSelectlist> unitSelectlists = new List<UnitSelectlist>();

            foreach (var item in pro)
            {
                if (unitSelectlists.Count() < 1)
                {
                    unitSelectlists.Add(new UnitSelectlist
                    {
                        unit = item.Unit
                    });
                }
                else
                {
                    var kt1 = unitSelectlists.Where(o => o.unit == item.Unit).ToList();
                    if (kt1.Count() < 1)
                    {
                        unitSelectlists.Add(new UnitSelectlist
                        {
                            unit = item.Unit
                        });
                    }

                }

            }
            ViewBag.unit = unitSelectlists.ToList();
            ViewBag.product = pro;
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            ViewBag.datenow = DateTime.Now;
            if (kt != null)
            {

QLK.Website/Views/Output/Create.cshtml
@model QLK.Website.Model.Bill

@{
    ViewBag.Title = "Create";
}

<h2 class="text-center">Thêm mới phiếu xuất</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.BillID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillID, "", new { @class = "text-danger" })
            </div>
    </div>*@

    <div class="form-group">
        @*@Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>*@
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.WarehouseID, "Tên kho", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 has-success">
        @Html.DropDownList("WarehouseID", new SelectList(ViewBag.Warehouses, "WarehouseID", "WarehouseName"))
        @Html.ValidationMessageFor(model => model.WarehouseID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class=" text-center col-md-6">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
        <div class="btn btn-danger">
            @Html.ActionLink("Trở về", "Index")

        </div>
    </div>
</div>
}

QLK.Website/Views/Output/CreateOpPartial.cshtml
@model QLK.Website.Model.DetailBill
@{
    Layout = null;
}
div>
<form id="myForm">
    @Html.HiddenFor(model => model.BillID)
    <div class=" has-success">
        <label>Mã mặt hàng</label>
        @*@Html.DropDownList("ProductId", new SelectList(ViewBag.product, "ProductID", "ProductName"), new { @class = "form-control", required = "required" })*@
        @Html.TextBoxFor(model => model.Product.ProductName, new { @class = "form-control", required = "required" })
    </div>
    <br />
    <div class=" has-success">
        <label>Đơn vị tính</label>
        @Html.TextBoxFor(model => model.Unit, new { @class = "form-control", required = "required" })
    </div>
    <br />
    <div class=" has-success">
        <label>Số lượng</label>
        
        @Html.TextBoxFor(model => model.Quantity, new { @class = "form-control", required = "required" })
    </div>

    <br />
    <div class="text-right">
        <a href="#" id="btnSubmit" class="btn btn-primary">Lưu</a>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Trở lại</button>
    </div>
</form>

<script>
    $(document).ready(function () {
        $("#btnSubmit").click(function () {

            var myformdata = $("#myForm").serialize();
            $.ajax({

                type: "POST",
                url: "/Output/Edit",
                data: myformdata,
                success: function (data) {
                    if (data == true) {

                        window.location.href = "/Danh-sach-phieu-xuat";
                    }
                    else {
                        alert("Lỗi! không thể chỉnh phiếu xuất này!");
                    }

                }

            })
        })
    })
</script>

QLK.Website/Views/Output/Delete.cshtml
@model QLK.Website.Model.Importcoupon

@{
    Layout = null;
    //ViewBag.Title = "Index";
}

<div class="modal fade" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title">Xác nhận</h4>
            </div>
            <div class="modal-body">
                <h3>Bạn có chắc muốn xóa nhà cung cấp này?</h3>
                <div>
                    <hr />
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>ImportID</th>
                            <td>@Html.DisplayFor(model => model.ImportID)</td>
                        </tr>
                        <tr>
                            <th>WarehouseID</th>
                            <td>@Html.DisplayFor(model => model.WarehouseID)</td>
                        </tr>
                        <tr>
                            <th>Date</th>
                            <td>@Html.DisplayFor(model => model.Date)</td>
                        </tr>
                    </table>
                </div>
            </div><!-- /.modal-body -->
            <div class="modal-footer">
                @using (Html.BeginForm("Delete", "Output", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-actions no-color text-center">
                        <input type="submit" value="Xóa" class="btn btn-danger" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
                    </div>
                }
            </div><!-- /.modal-footer -->
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

QLK.Website/Views/Output/Edit.cshtml
@model QLK.Website.Model.Bill

@{
    ViewBag.Title = "Chỉnh sửa hóa đơn xuất";
}


<div class="row">
    <!-- left column -->
    <div class="col-md-12">
        <!-- general form elements -->
        <!-- Form Element sizes -->
        <div class="box box-success">
            <div class=" with-border">@*box-header*@
                        <h3 class="box-title">@ViewBag.Title</h3>
                    </div>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(m => m.BillID)
        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.BillID)

            <div class="form-group">
                @Html.LabelFor(model => model.Date, "Ngày tạo hóa đơn", htmlAttributes: new { @class = "control-label col-md-2" })
                @*<div class="col-md-10 has-success">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "datetime" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>*@
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Warehouse.WarehouseName, "Tên kho", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10 has-success">
                    @Html.EditorFor(model => model.Warehouse.WarehouseName, new { htmlAttributes = new { @class = "form-control" } })
                    @*@Html.DropDownList("WarehouseID", null, htmlAttributes: new { @class = "form-control" })*@
                    @Html.ValidationMessageFor(model => model.Warehouse.WarehouseName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.BillName, "Tên phiếu xuất", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10 has-success">
                    @Html.EditorFor(model => model.BillName, new { htmlAttributes = new { @class = "form-control" } })
                    @*@Html.DropDownList("WarehouseID", null, htmlAttributes: new { @class = "form-control" })*@
                    @Html.ValidationMessageFor(model => model.BillName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row">
                <div class=" text-center col-md-6">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
                <div class="btn btn-danger">
                    @Html.ActionLink("Trờ về", "Index")

                </div>
            </div>
        </div>

            }
            <br />
        </div>
    </div>
</div>

QLK.Website/Views/Output/EditOpPartial.cshtml
@model QLK.Website.Model.Bill

@{
    Layout = null;
}
<div>
    <form id="myForm">
        @Html.HiddenFor(model => model.BillID , new { @id ="BillID" })

        @Html.TextBoxFor(model => model.Date, new { @class = "form-control", hidden = "hidden" ,id="Date" })
        @*@Html.TextBoxFor(model => model.Photo, new { @class = "form-control", hidden = "hidden" })*@
        <div class="row">
            <div class="form-group">
                <div class="col-lg-4">
                    <label>Ảnh</label>
                </div>
                <div class="col-lg-8">
                    @foreach (var ite in ViewBag.UploadphotoBill)
                    {
                        if (ite.IdBill == Model.BillID)
                        {
                            <img src="@Url.Content(ite.Path)" style="height:50px;width:50px">
                        }

                    }

                </div>

            </div>
        </div>
        <input type="file" name="file2" id="file2" multiple accept="image/*" style="width:100%;" />
        <div class="form-group">
            <label>Tên kho</label>
            @*@Html.TextBoxFor(model => model.Warehouse.WarehouseName, new { @class = "form-control", @placeholder = "" })*@
            @Html.DropDownList("WarehouseID", new SelectList(ViewBag.ware, "WarehouseID", "WarehouseName"), new { @class = "form-control", required = "required" })
        </div>

        <div class="form-group">
            <label>Tên phiếu xuất</label>
            @Html.TextBoxFor(model => model.BillName, new { @class = "form-control", @placeholder = "" , id= "BillName1" })
        </div>
        <div class="text-right">
            <a href="#" id="btnSubmit" class="btn btn-primary">Lưu</a>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Trở lại</button>
        </div>
    </form>
</div>

<script>
    $(document).ready(function () {
        $("#btnSubmit").click(function () {
             var fd = new FormData();
            $.each($("input[name='file2']")[0].files, function (i, file) {
                fd.append('file', file);
            });
            fd.append('BillID', $('#BillID').val());
            fd.append('Date', $('#Date').val());
            fd.append('WarehouseID', $('#WarehouseID').val());
            fd.append('BillName', $('#BillName1').val());
            $.ajax({
                type: "POST",
                 url:'@Url.Action("Edit")',
                data: fd,
                processData: false,
                contentType: false,
                success: function (_data) {

                    if (_data == true) {
                        window.location.href = "/Danh-sach-phieu-xuat";
                    }
                    else {
                        alert("Lỗi! không thể chỉnh phiếu xuất này!");
                    }

                }

            })






            //var myformdata = $("#myForm").serialize();
            //$.ajax({

            //    type: "POST",
            //    url: "/Output/Edit",
            //    data: myformdata,
            //    success: function (data) {
            //        if (data == true) {

            //            window.location.href = "/Danh-sach-phieu-xuat";
            //        }
            //        else {
            //            alert("Lỗi! không thể chỉnh phiếu xuất này!");
            //        }

            //    }

            //})
        })
    })
</script>

QLK.Website/Views/Output/PartialDetail.cshtml
@*@model QLK.Website.Model.Bill*@
@*@model  IEnumerable<QLK.Website.Model.DetailBill>*@

@using PagedList.Mvc;
@model PagedList.IPagedList<QLK.Website.Model.DetailBill>
@{
    ViewBag.Title = "Chi tiết phiếu xuất";
    Layout = null;
}
<div class="row">
    <!-- left column -->
    <div class="col-md-12">
        <!-- general form elements -->
        <!-- Form Element sizes -->
        <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title">@ViewBag.Title</h3>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            @*<a href="#" class="btn btn-success" onclick="CreateOuput(.)"> <i class="fa fa-plus"></i> Thêm mới</a>*@
                            <a href="#" class="btn btn-success" data-toggle="modal" data-target="#detailform"> <i class="fa fa-plus"></i>Thêm mới</a>
                        </div>
                    </div>
                    <div class="col-lg-6">

                    </div>
                </div>
                <div class="box box-primary">
                    <form id="myForm">
                        <table class="table table-bordered table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        Mã phiếu xuất kho
                                    </th>
                                    <th>
                                        Mã chi tiết phiếu xuất kho
                                    </th>
                                    <th>
                                        Mã hàng
                                    </th>
                                    <th>
                                        Ngày xuất
                                    </th>
                                    <th>
                                        Đơn giá
                                    </th>
                                    <th>
                                        Số lượng
                                    </th>
                                </tr>

                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.BillID)
                                            @*@item.BillID*@
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.DetailBillID)
                                            @*@item.DetailBillID*@
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ProductID)
                                            @*@item.ProductID*@
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Bill.Date)
                                            @*@Model.Date*@
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Unit)
                                            @*@item.Unit*@
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Quantity)
                                            @*@item.Quantity*@
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="text-center">
    Trang @(Model.PageCount < Model.PageNumber ? 0: Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("DetailsPar", new { page }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "Output_area"}))
</div>


<div class="modal fade" id="detailform" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h1 class="modal-title text-center">Thêm chi tiết phiếu xuất</h1>
            </div>
            <form action="" method="post" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="form-group">
                        <label>Mã phiếu xuất</label>
                        <input type="text" name="BillID" id="BillID" class="form-control" required />
                    </div>
                    <div class="form-group">
                        <label>Mã mặt hàng</label>
                        <input type="text" name="ProductID" id="ProductID" class="form-control" required />
                    </div>
                    <div class="form-group">
                        <label>Đợn vị tính </label>
                        <input type="text" name="Unit" id="Unit" class="form-control" required />

                    </div>
                    <div class="form-group">
                        <label>Số lượng</label>
                        <input type="text" name="Quantity" id="Quantity" class="form-control" required />
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="button" id="btnCreate" class="btn btn-primary" value="Lưu">

                    <button type="button" class="btn btn-danger" data-dismiss="modal">Trở lại</button>
                </div>
            </form>
        </div>
    </div>
</div>


<script>


    $(document).ready(function () {

        $("#btnSave").click(function () {
            var supplierFormData = $("#detailoutput1").serialize();
            $.ajax({
                type: "POST",
                url: "DetailOutput/Create",
                data: supplierFormData,
                success: function (data) {
                    if (data == true) {
                        window.location.href = "/Danh-sach-chi-tiet-phieu-xuat";
                    }
                    else {
                        alert("Lỗi !! Không thể thêm mới chi tiết phiếu xuất này!")
                    }
                }
            })
        })

        $('#btnCreate').click(function () {
            var fd = new FormData();
            fd.append('BillID', $('#BillID').val());
            fd.append('ProductID', $('#ProductID').val());
            fd.append('Unit', $('#Unit').val());
            fd.append('Quantity', $('#Quantity').val());
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Create1", "DetailOutput")',
            data: fd,
            processData: false,
            contentType:false,
            success: function (data) {
                //alert(data);
                //return;
                if (data == true) {
                    window.location.href = "/Danh-sach-phieu-xuat";
                }
                else {
                    alert("Lỗi!! không thể thêm mặt hàng này !");
                }

                //$('#data').empty();
                //$('#data').append(data);

            }

        });
    });
    })


</script>